name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    
    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '7.0'
        
    - uses: actions/checkout@v3


    - name: Run exercsie 1
      run: make run-1
